/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'oleclangfjaran' at '11/2/15 5:53 PM' with Gradle 2.8
 *
 * @author oleclangfjaran, @date 11/2/15 5:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
